##### ~~~~~~~~~~~~ ######
##### ARRAY CONFIG ######
##### ~~~~~~~~~~~~ ######


### COMMON ATTRIBUTES ###
#########################

# Not sure if this is needed in the yaml or only in the ddbb.
# We can load these common attributes into any of our objects.
CommonHistory: &defaultCommonAttributes
  serialNumber: null
  commisioningDate: null
  decomissioningDate: null

CommonProperties: &defaultcommonprop
  ID: null # Number/Code to identify the pixel
  Description: null

Table: &defaulttable
  <<: *defaultcommonprop
  # Table should contain as a first column an ID tag.
  Header: []
  Data:  []
  Units: []

### FUNDAMENTAL TYPES FOR CAMERAS ###
#####################################

# PIXELS

PhotoDetector: &defaultphotodetector
  <<: *defaulttable

PixelElectronics: &defaultpixelelectronics
  <<: *defaulttable

PixelOptics: &defaultpixeloptics
  <<: *defaulttable

Pixel: &defaultpixel
  <<: *defaulttable
  # Properties photodetector, electronics, optics, type, posX, posY, posZ, area, active ...

# DRAWERS: CLUSTERS OF PIXELS WITH SOME COMMON PROPERTIES (OPTIONAL)
DrawerElectronics: &defaultdrawerelectronics
  <<: *defaulttable

Drawer: &defaultdrawer
  <<: *defaulttable

# CAMERA: ARRAY OF PIXELS/DRAWERS
CameraOptics: &defaultcameraoptics
  <<: *defaulttable

Camera: &defaultcamera
  <<: *defaultcommonprop
  drawers: {}
  pixels:
    <<: *defaultpixel

### FUNDAMENTAL TYPES FOR OPTICS ###
####################################

Panel: &defaultpanel
  <<: *defaulttable

Mirror: &defaultmirror
  <<: *defaulttable

TelescopeOptics: &defaultoptics
  <<: *defaulttable

### FUNDAMENTAL TYPES FOR MOUNT ###
###################################

Mount: &defaultmount
  <<: *defaulttable


### FUNDAMENTAL TYPES FOR MONITORUNIT ###
#########################################

MonitorUnit: &defaultmonitor
  <<: *defaulttable


### FUNDAMENTAL TYPES FOR TELESCOPE ###
#######################################

Telescope: &defaultteslescope
  <<: *defaulttable
  # should include monitorunit, mount, optics, camera


### FUNDAMENTAL TYPES FOR ARRAY ###
###################################

Array: &defaultarray
  <<: *defaulttable

AuxiliaryInstrument: &defaultauxiliaryinstrument
  <<: *defaulttable

Site: &defaultsite
  <<: *defaulttable
  # should have lat, lon, alt,
  # should include a list of auxliary instruments
  ID: null
  name: null # the name of the site.
  latitude: null
  longitude: null
  altitude: null
  auxiliaryInstruments: []
  array:
    <<: *defaultarray

Observatory: &defaultobservatory
  <<: *defaulttable
